# R code for Ayhan's bulk RNA-seq analysis
# Zhaoning Wang
# 2021-02-14

library(edgeR)  
library(pheatmap)
library(ggplot2)

counts <- read.delim("RNAseq_RawCountTable.txt", header=TRUE, row.names=1) # This file can be found from GEO #GSE169190.

dim(counts) 
head(counts) 
dgList <- DGEList(counts=counts, genes=rownames(counts)) 
dgList$samples
head(dgList$counts)
head(dgList$genes)
countsPerMillion <- cpm(dgList) 
summary(countsPerMillion)
countCheck <- countsPerMillion > 1
head(countCheck)
keep <- which(rowSums(countCheck) >= 3)
dgList <- dgList[keep,]
summary(cpm(dgList))
dgList <- calcNormFactors(dgList, method="TMM") 
plotMDS(dgList)

## estimate the dispersion, estimate common dispersion first then Tagwise dispersion
d1 <- estimateCommonDisp(dgList, verbose=T)
d1 <- estimateTagwiseDisp(d1)

#Calculate DEG...
colnames(counts) <- c("DMD","DMD","DMD","cDMD_RF","cDMD_RF","cDMD_RF","cDMD_ES","cDMD_ES","cDMD_ES")

Condition__current <- factor(c("DMD","DMD","DMD","cDMD_RF","cDMD_RF","cDMD_RF","cDMD_ES","cDMD_ES","cDMD_ES"))
Timepoint__current <- factor(c("1","1","1","1","1","1","1","1","1"))
targets__current <- data.frame(Sample=colnames(dgList),Condition__current,Timepoint__current)
Group__current <- factor(paste(targets__current$Condition__current,targets__current$Timepoint__current,sep="."))
cbind(targets__current,Group=Group__current)
design <- model.matrix(~0+Group__current) 
colnames(design) <- levels(Group__current)
dgList <- estimateDisp(dgList, design, robust=TRUE)
dgList$common.dispersion
plotBCV(dgList)
fit <- glmFit(dgList, design)

my.contrasts <- makeContrasts(
  cDMD_RFvsDMD = cDMD_RF.1-DMD.1,
  levels=design)
lrt = glmLRT(fit, contrast=my.contrasts[,"cDMD_RFvsDMD"])
tab6 <- topTags(lrt, n=Inf)
write.table(tab6, file="cDMD_RFvsDMD.edgeR.txt")

my.contrasts <- makeContrasts(
  cDMD_ESvsDMD = cDMD_ES.1-DMD.1,
  levels=design)
lrt = glmLRT(fit, contrast=my.contrasts[,"cDMD_ESvsDMD"])
tab6 <- topTags(lrt, n=Inf)
write.table(tab6, file="cDMD_ESvsDMD.edgeR.txt")


my.contrasts <- makeContrasts(
  cDMD_ESvscDMD_RF = cDMD_ES.1-cDMD_RF.1,
  levels=design)
lrt = glmLRT(fit, contrast=my.contrasts[,"cDMD_ESvscDMD_RF"])
tab6 <- topTags(lrt, n=Inf)
write.table(tab6, file="cDMD_ESvscDMD_RF.edgeR.txt")


###########################################################
# Volcano plots

voldata1 <- read.delim(file.choose(), header=TRUE) # This file is generated by adding a "LogPValue" column calculated from the edgeR results.

voldata1$threshold <- as.factor(ifelse(voldata1$FDR < 0.01 & abs(voldata1$logFC) >=1,ifelse(voldata1$logFC >=1 ,'Up','Down'),'Not'))

# y intercept: RFvsDMD=2.49; ESvsDMD=2.60; ESvsRF=2.71.

ggplot(data=voldata1, aes(x=logFC, y=LogPValue,  colour=threshold, text = paste("Gene:",genes))) +
  scale_color_manual(values=c("blue", "dimgrey","red")) +
  geom_point(alpha=0.4, size=1.75) +
  xlab("log2 fold change") + ylab("-log10 p-value") + 
  geom_vline(xintercept=c(-1,1),lty=4,col="grey",lwd=0.5) + geom_hline(yintercept = 2.49,lty=4,col="grey",lwd=0.5) +
  theme(legend.position="none")+
  xlim(-15,15) + ylim(0,200) # change y-intersection based on FDR cutoff

######################################################
# DESeq for PCA Analysis

library(DESeq2)
library(ggplot2)
library("S4Vectors")
library("DelayedArray")

counttable <- read.delim(file.choose(), header=TRUE)  #load data file
meta.data.design <- read.delim(file.choose(), header=TRUE)  #load data file

dds <- DESeqDataSetFromMatrix(countData=counttable, 
                              colData=meta.data.design, 
                              design=~dex, tidy = TRUE)
dds <- DESeq(dds)
res <- results(dds)
head(results(dds, tidy=TRUE)) 
summary(res)

res <- res[order(res$padj),]
head(res)

par(mfrow=c(1,1))
# Make a basic volcano plot
with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-3,3)))

# Add colored points: blue if padj<0.01, red if log2FC>1 and padj<0.05)
with(subset(res, padj<.01 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
with(subset(res, padj<.01 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))

vsdata <- vst(dds, blind=FALSE)
plotPCA(vsdata, intgroup="dex") 
plotPCA(vsdata, intgroup="id") 

##############################################
# Heatmaps

# Figure 3A

heatmap_data <- read.delim(file.choose(), header=TRUE, row.names = 1) # This file is generated by DEG (from edgeR results) x RPKM table (calculated elsewhere, can be found from the GEO #GSE169190)

pheatmap(heatmap_data, cluster_rows = TRUE, cluster_cols = FALSE, annotation_row = rowanno, scale = "row", annotation_names_col = TRUE,show_rownames = TRUE, fontsize = 12, fontsize_row = 1, color = colorRampPalette(c("blue2","white","red2"))(200))

# Figures 3C, 3D

heatmap_data <- read.delim(file.choose(), header=TRUE, row.names = 1) # This file is generated by [Genes of interest] x RPKM table (calculated elsewhere, can be found from the GEO #GSE169190)

pheatmap(heatmap_data, cluster_rows = FALSE, cluster_cols = FALSE, scale = "row", annotation_names_col = TRUE,show_rownames = TRUE, fontsize = 9,fontsize_row = 8, color = colorRampPalette(c("blue2","white","red2"))(200))
